#!/bin/bash
file=$1
[[ -f "${file}.json" ]] || fingerprint "${file}" > "${file}.json"
echo getTags \"${file}.json\" \"${file}\" \| bash
[[ ! $(jq '.results' "${file}.json") == "null" ]] && getTags "${file}.json" "${file}" | bash

rm "${file}.json"