#!/bin/bash
file=$1
fpcalc "$file" | awk -F'=' '/DURATION/ {dur=$2} /FINGERPRINT/ {fingerprint=$2} END{print "curl -F \"fingerprint=" fingerprint "\" \"https://api.acoustid.org/v2/lookup?client=whUpfZZrMt&meta=recordings+tracks+releases+releasegroups&duration=" dur "\""}' | bash 2>/dev/null && echo
